# Site settings
title: material
email: naveen@pixelblenders.com
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Naveen, a freelance front-end developer
  and UI designer. Check out my projects on GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://naveenshaji.github.io/material" # the base hostname & protocol for your site
twitter_username: navvenshady
github_username:  naveenshaji
css: "cyan"
scroll-cursor: "#00BCD4"
scroll-rail: "#0097A7"

# Build settings
markdown: kramdown
highlighter: null #pygments
lsi: false
safe: false
